  # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-export-windows

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: UHP
  GODOT_VERSION: 3.4.4

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Print variables
        run : echo $GODOT_VERSION
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable.mono ~/.local/share/godot/templates/$GODOT_VERSION.stable.mono
      - run: |
          # install rsync
          apt-get update && apt-get install -y rsync
      - run: |
          # make file runnable
          chmod +x $GITHUB_WORKSPACE/.github/rsync_wrapper.sh
      - name: Web Build
        run: |
          # add the export directory
          mkdir ./$EXPORT_NAME
      - run: |
          #run rsync wrapper script
          $GITHUB_WORKSPACE/.github/rsync_wrapper.sh -Rr . ./$EXPORT_NAME
      - run: |
          # navigate to export dir
          cd $EXPORT_NAME
          mkdir -v -p export
      - run: |
          # make export script runnable
          chmod +x $GITHUB_WORKSPACE/.github/export_godot.sh
      - run: |
          #run godot export
          mkdir -p $GITHUB_WORKSPACE/export/Windows/
          godot -v --export WindowsDesktop --no-window --quiet || true
      - run: |
          # list dir
          ls $GITHUB_WORKSPACE/export/Windows/uhp.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: WindowsDesktop.zip
          path: ./export/WindowsDesktop/WindowsDesktop.zip

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: utp
          ITCH_USER: hackerferret
          PACKAGE: ./export/WindowsDesktop/WindowsDesktop.zip
    