  # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-ci

on:
  push:
    branches: [ release ]

env:
  EXPORT_NAME: UHP
  GODOT_VERSION: 3.4.4

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Print variables
        run : echo $GODOT_VERSION
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable.mono ~/.local/share/godot/templates/$GODOT_VERSION.stable.mono
      - run: |
          # install rsync
          apt-get update && apt-get install -y rsync
      - run: |
          # make file runnable
          chmod +x $GITHUB_WORKSPACE/.github/rsync_wrapper.sh
      - name: Web Build
        run: |
          # add the export directory
          mkdir ./$EXPORT_NAME
      - run: |
          #run rsync wrapper script
          $GITHUB_WORKSPACE/.github/rsync_wrapper.sh -Rr . ./$EXPORT_NAME
      - run: |
          # navigate to export dir
          cd $EXPORT_NAME
          mkdir -v -p export
      - run: |
          # make export script runnable
          chmod +x $GITHUB_WORKSPACE/.github/export_godot.sh
      - run: |
          #run godot export
          $GITHUB_WORKSPACE/.github/export_godot.sh "HTML5" $GITHUB_WORKSPACE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: ${{ env.EXPORT_NAME }}/export

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: utp
          ITCH_USER: hackerferret
          PACKAGE: ${{ env.EXPORT_NAME }}/export/HTML5/HTML5.zip
    
