  # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-ci

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: UHG
  GODOT_VERSION: 3.4.2

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
      - run: |
          pwd
      - run: |
          ls -a /github/home/.local/share/godot/templates
      - run: |
          ls -a ~/.local/share/godot/templates
      - run: |
          [ -d "/github/home/" ] && echo "Directory /github/home/ exists."
      - run: |
          [ -d "~/.local/share/godot/templates" ] && echo "Directory ~/.local/share/godot/templates exists."
      - run: |
          ls -a /github/home/
      - run: |
          ls -a /github/home/.local/share/godot/templates/
      - run: |
          mv /github/home/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - run: |
          apt-get update && apt-get install -y rsync

      - name: Web Build
        run: |
          cd project
          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          cd $EXPORT_NAME
          mkdir -v -p export
          godot -v --export "HTML5" export/index.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: project/${{ env.EXPORT_NAME }}/export

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: uhg
          ITCH_USER: hackerferret
          PACKAGE: project/${{ env.EXPORT_NAME }}/export