  # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-ci

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: UHG
  GODOT_VERSION: 3.4.4

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Print variables
        run : echo $GODOT_VERSION
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          ls /root/.local/share/godot/
          ls /root/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable.mono ~/.local/share/godot/templates/$GODOT_VERSION.stable.mono
          apt-get update && apt-get install -y rsync


      - name: Web Build
        run: |
          REAL_RSYNC=/usr/bin/rsync
          IGNOREEXIT=24
          IGNOREOUT='^(file has vanished: |rsync warning: some files vanished before they could be transferred)'

          # If someone installs this as "rsync", make sure we don't affect a server run.
          for arg in "${@}"; do
              if [[ "$arg" == --server ]]; then
            exec $REAL_RSYNC "${@}"
            exit $? # Not reached
              fi
          done

          set -o pipefail

          # This filters stderr without merging it with stdout:
          { $REAL_RSYNC "${@}" 2>&1 1>&3 3>&- | grep -E -v "$IGNOREOUT"; ret=${PIPESTATUS[0]}; } 3>&1 1>&2

          if [[ $ret == $IGNOREEXIT ]]; then
              ret=0
          fi

          exit $ret        

          mkdir ./$EXPORT_NAME
          rsync -Rr . ./$EXPORT_NAME
          cd $EXPORT_NAME
          mkdir -v -p export
          godot -v --export "HTML5" export/index.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: project/${{ env.EXPORT_NAME }}/export

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: uhg
          ITCH_USER: hackerferret
          PACKAGE: project/${{ env.EXPORT_NAME }}/export