  # Adapted from https://raw.githubusercontent.com/RudyMis/Bubbles/master/.github/workflows/godot-ci.yml

name: godot-export-windows

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: UHP
  GODOT_VERSION: 3.4.4

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run : |
          echo GODOT_VERSION: $GODOT_VERSION
          echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      - run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable.mono ~/.local/share/godot/templates/$GODOT_VERSION.stable.mono
      - run: |
          #run godot export
          godot -v --export WindowsDesktop --no-window --quiet || true
      - run : |
          echo "GODOT_VERSION: $GODOT_VERSION"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo $(pwd)
          echo "------------------"
          echo "----ls GITHUB_WORKSPACE/Export------------"
          ls $GITHUB_WORKSPACE/Export
          echo "----ls------------"
          ls
          echo "------------------"
          echo "github.workspace: ${{ github.workspace }}"
          echo "------------------"

      - uses: actions/upload-artifact@v2
        with:
          name: uhp.exe
          path: /__w/Themed-Horror-Jam-5/Themed-Horror-Jam-5/Export/WindowsDesktop/uhp.exe

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: utp
          ITCH_USER: hackerferret
          PACKAGE: ${{ github.workspace }}/Export/Windows/uhp.exe

